site_name: dwarf-ice3-gt4py

nav:
  - Home: index.md
  - Translation Notes: translation_notes.md
  - phyex_gt4py:
    - stencils: 
      - aro_filter: phyex_gt4py/stencils/aro_filter.md
      - ice_adjust: phyex_gt4py/stencils/ice_adjust.md
    - components:
      - aro_adjust: phyex_gt4py/components/aro_adjust.md
      - ice_adjust: phyex_gt4py/components/ice_adjust.md
    - functions:
      - backup: phyex_gt4py/functions/backup
      - compute_ice_frac: phyex_gt4py/functions/compute_ice_frac
      - condensation_src_1d: phyex_gt4py/functions/condensation_src_1d
      - erf: phyex_gt4py/functions/erf
      - gamma: phyex_gt4py/functions/gamma
      - ice_adjust: phyex_gt4py/functions/ice_adjust
      - ice4_sedimentation_stat: phyex_gt4py/functions/ice4_sedimentation_stat
      - icecloud: phyex_gt4py/functions/icecloud
      - sign: phyex_gt4py/functions/sign
      - src_1d: phyex_gt4py/functions/src_1d
      - subgrid_mf: phyex_gt4py/functions/subgrid_mf
      - temperature: phyex_gt4py/functions/temperature
      - tiwmx: phyex_gt4py/functions/tiwmx

theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .

