site_name: dwarf-ice3-gt4py

nav:
  - Home: index.md
  - Translation Notes: translation_options.md
  - Scientific Notes: microphysique.md
  - ice3_gt4py:
    - stencils:
      - aro_filter: ice3_gt4py/stencils/aro_filter.md
      - ice_adjust: ice3_gt4py/stencils/ice_adjust.md
    - components:
      - aro_adjust: ice3_gt4py/components/aro_adjust.md
      - ice_adjust: ice3_gt4py/components/ice_adjust.md
    - functions:
      - backup: ice3_gt4py/functions/backup
      - compute_ice_frac: ice3_gt4py/functions/compute_ice_frac
      - condensation_src_1d: ice3_gt4py/functions/condensation_src_1d
      - erf: ice3_gt4py/functions/erf
      - gamma: ice3_gt4py/functions/gamma
      - ice_adjust: ice3_gt4py/functions/ice_adjust
      - ice4_sedimentation_stat: ice3_gt4py/functions/ice4_sedimentation_stat
      - icecloud: ice3_gt4py/functions/icecloud
      - sign: ice3_gt4py/functions/sign
      - src_1d: ice3_gt4py/functions/src_1d
      - subgrid_mf: ice3_gt4py/functions/subgrid_mf
      - temperature: ice3_gt4py/functions/temperature
      - tiwmx: ice3_gt4py/functions/tiwmx
    - phyex_common:
      - budget: ice3_gt4py/phyex_common/budget
      - constants: ice3_gt4py/phyex_common/constants
      - dimphyex: ice3_gt4py/phyex_common/dimphyex
      - nebn: ice3_gt4py/phyex_common/nebn
      - param_ice: ice3_gt4py/phyex_common/param_ice
      - phyex: ice3_gt4py/phyex_common/phyex
      - rain_ice_descr: ice3_gt4py/phyex_common/rain_ice_descr
      - rain_ice_param: ice3_gt4py/phyex_common/rain_ice_param
    - initialisation:
      - utils: ice3_gt4py/initialisation/utils
      - reference: ice3_gt4py/initialisation/reference
      - state: ice3_gt4py/initialisation/state
    - drivers:
      - config: ice3_gt4py/drivers/config

theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .
