site_name: dwarf-ice3-gt4py

nav:
  - Home: index.md
  - Translation Notes: translation_notes.md
  - phyex_gt4py:
    - stencils: 
      - aro_filter: phyex_gt4py/stencils/aro_filter.md
      - ice_adjust: phyex_gt4py/stencils/ice_adjust.md
    - components:
      - aro_adjust: phyex_gt4py/components/aro_adjust.md
      - ice_adjust: phyex_gt4py/components/ice_adjust.md

theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .

