[build-system]
requires = ['setuptools>=42', 'wheel']

[tool.setuptools_scm]

# As PMAPL-dycore
[project.optional-dependencies]
development = ['black>=22.6.0', 'flake8', 'ipdb', 'ipython', 'mypy', 'pre-commit']
distributed = [
    #'ghex @ git+https://github.com/stubbiali/GHEX.git@py_bindings_debug#egg=ghex&subdirectory=bindings/python',
        'ghex @ git+https://github.com/stubbiali/GHEX.git@refactor-python-bindings-fix#egg=ghex&subdirectory=bindings/python',
    'netCDF4 @ git+https://github.com/stubbiali/netcdf4-python.git@fvm#egg=netCDF4'
]
gpu = [
    # required to compile CuPy from source
    'cython==0.29.36',
    'cupy'
]
gpu-cuda11x = ['cupy-cuda11x']
gpu-cuda12x = ['cupy-cuda12x']
gpu-rocm = [
    # required to compile CuPy from source
    'cython==0.29.36',
    'cupy==12.3.0',
    # required until ROCm/HIP support is not included in a release of GT4Py
    #'gt4py[dace] @ git+https://github.com/GridTools/gt4py.git@054e4e6a3416e9b704da41574e7e0ea7913b8006'
        'gt4py[dace] @ git+https://github.com/GridTools/gt4py.git@6b269bdf4bdc9e6e6c896b03c43f73c6342eb443'
]
testing = ['numba==0.56.0', 'pytest>=7.0']

[tool.black]
line-length = 100
target-version = ['py37', 'py38', 'py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''
