[tool.poetry]
name = "dwarf-phyex-gt4py"
version = "0.1.0"
description = "Externalized App for ICE3 Microphysics in GT4Py"
authors = ["Loïc Maurin <loic.maurin@meteo.fr>"]
license = "\"CeCILL-C\""
readme = "README.md"
packages = [
    { include = "ice3_gt4py", from = "src" },
    { include = "testprogs_data", from = "src"},
    { include = "test_util"     , from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
ifs-physics-common = {git = "https://github.com/maurinl26/ifs-physics-common.git"}
gt4py = "==1.0.3"


[tool.poetry.group.dev.dependencies]
virtualenv = "^20.25.0"
pre-commit = "^3.5.0"

[tool.poetry.scripts]
ice-adjust = "ice3_gt4py.driver.cli:run_ice_adjust"
rain-ice = "ice3_gt4py.driver.cli:run_rain_ice"
extract-ice-adjust-data = "testprogs_data.main:extract_data_ice_adjust"
extract-rain-ice-data = "testprogs_data.main:extract_data_rain_ice"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
